import { resolve } from 'node:path'

import tailwindcss from '@tailwindcss/vite'
import react from '@vitejs/plugin-react'
import { doors, serves } from 'kehikot-module-protocol/serve'
import { defineConfig } from 'vite'

import { BUILD, MANIFEST, TICKET, answer } from './doors.ts'
import { ID, PREFERRED_PORT } from './manifest.ts'

/**
 * Every door, served by the process that serves the page, through the protocol's `doors()`: the
 * manifest, `/app` (generated, with the write ticket and the build printed into it), and
 * `/healthz`, `/mcp` and `/api/*` through `answer` in doors.ts. A module is ONE ORIGIN: the host
 * refuses an `entry` anywhere else, and a store on a second port would make the page's own `/api`
 * calls cross-origin. See the protocol's docs/module-plumbing.md.
 *
 * `/app` is claimed by `doors()` before Vite's resolver sees it: under Vite dev an extensionless
 * `/app` next to `src/app.tsx` would otherwise answer with compiled JavaScript, which a frame
 * loads happily and runs nothing from.
 *
 * - No `server.cors`: the manifest declares storage, so the page is same-origin
 *   and a permissive CORS header would only let strangers read the ticket —
 *   which here is the ticket that sends a review.
 * - No alias for `kehikot-module-protocol`: resolve it through its exports, as
 *   the host does. The `@` alias points inside this repo, for shadcn.
 * - No `server.port`: `serves()` (first, so it claims before anything else)
 *   decides it from PREFERRED_PORT and keeps the registration true.
 * - No build: the page is generated by `doors()`.
 * - `base: './'`, because a host frames this at whatever address it wrote down.
 */
export default defineConfig({
  base: './',
  plugins: [
    serves({ id: ID, prefer: PREFERRED_PORT }),
    doors({ manifest: MANIFEST, answer, build: BUILD, page: { title: 'Review', ticket: TICKET } }),
    react(),
    tailwindcss(),
  ],
  resolve: { alias: { '@': resolve(import.meta.dirname, 'src') } },
})
